[build-system]
requires = ['setuptools',
			'scipy','ipython','matplotlib','tqdm','numpy','ephem',
			'pymeeus','regex','pandas','tabulate','numpy','spiceypy',
			'pyplanets'
	    ]
build-backend = "setuptools.build_meta"
